### ISSUE TITLE
Nodes that appear to exist but don't

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#104]
This issue is to report that the drop-down menu suggests that certain nodes exist (e.g., airborne particulate matter, asthma exacerbations), but don't actually appear to be in the graph. The issue may be because the drop-down menu pulls from Name Resolver and does not necessarily reflect what is in ROBOKOP KG. This is confusing (and frustrating) to users.

I think this may be a general Translator issue, as well.

**Comment by cbizon** [comment]
This should now be resolved with later changes to how we use name resolver.  Reopen if you see this again.
