### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#110]
This issue is to report a 500 error for a query that previously ran.

![image](https://user-images.githubusercontent.com/26254388/220211617-4533e17e-dc24-4c22-ad0e-94e31e8508a5.png)

**Comment by cbizon** [comment]
It's working now:
![image](https://user-images.githubusercontent.com/10744350/225414402-b735d246-8e8d-47da-8518-cd43dff909f3.png)
