### ISSUE TITLE
Query no longer yields results

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#111]
This issue is to report that a query than ran successfully a few weeks ago no longer does.

Original results:

![image](https://user-images.githubusercontent.com/26254388/221229954-de2f0166-cca3-4cc8-b4fb-be9ecd7bf783.png)

New "results":

![image](https://user-images.githubusercontent.com/26254388/221230071-4239c870-962d-418b-92ba-212ab3672a35.png)

**Comment by cbizon** [comment]
I received 0 results.   One thing I notice is that there are different labels for Myd88 and MYD88.  I wonder if this is human vs non-human genes or something.   If so, then it points towards a problem with the chooser.  There are quite a few entities that it could be in there.

Also, this query is a bit odd because it has a cartesian product on Myd88.  That is if there are N answers to the left side of the query and M answers to the right then you will end up with NxM answers, which will be harder to understand than running these two independently

**Comment by cbizon** [comment]
Taking off particular matter and changing Myd88 to gene takes forever.  Not sure if the new transpiler is in place yet.

**Comment by karafecho** [comment]
The different labels issue is a separate one, I think, as I believe I tried both the second time I attempted to run the query. However, that is worth testing.

**Comment by karafecho** [comment]
Now there's a node normalization issue:

![image](https://user-images.githubusercontent.com/26254388/226377365-3e3b8698-ad4a-4bb2-a1bd-ae8dd2a5be07.png)

**Comment by cbizon** [comment]
That's bizarre, it seems to work for everything except myd...

**Comment by karafecho** [comment]
This is a new issue, however, as I selected both Myd88 and MYD88 in prior queries. There were quite a few options to select from, as I recall.

**Comment by cbizon** [comment]
Yeah, I tracked it down to a nodenorm error that maybe has to do with a forced reboot a few days ago.     Gaurav is looking into it now

**Comment by beasleyjonm** [comment]
![Screenshot 2023-03-24 142012](https://user-images.githubusercontent.com/85600465/227608280-6743dcf1-6a4b-4ec9-ae56-0fa0d5e46acd.png)

I got the original results to work again, but it only works when MYD88 (NCBIGene:4615) is selected. There were 4 options, for myd88 that showed up in the query builder (myd88, myd88, MYD88, MYD88) and only one returned results.

**Comment by karafecho** [comment]
The query works for me now, too, although I noticed two things:

1. There are at least 10 options for Myd88, although as Jon-Michael notes, only one returns results.
2. The last answer does not appear to be ranked properly.

![image](https://user-images.githubusercontent.com/26254388/228026955-8c4801a3-78e1-49e6-a2d9-2075c284fb08.png)

**Comment by cbizon** [comment]
This appears to be down to the taxon issue again. Closing as something to be fixed by #205
