### ISSUE TITLE
Open-ended one-hop query does not run

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#114]
A query seeking all 'named things' related to 'cystic fibrosis' runs for a while and then stops running, with nothing returned to users, including an error message or a 'no results found' message.

![image](https://user-images.githubusercontent.com/26254388/223214929-4a98fe66-0705-4ba2-b481-35c4a892aa19.png)

**Comment by cbizon** [comment]
The current behavior is also not great - it runs and then the error message tries to hold the json response so it's a wall of red.

**Comment by hina-shah** [comment]
I cannot reproduce this now. Maybe this has been resolved with the newer deployments? @cbizon, @Woozl

**Comment by Woozl** [comment]
> I cannot reproduce this now. Maybe this has been resolved with the newer deployments? @cbizon, @Woozl 

If it's working now, we should close it. There are numerous issues regarding the error messaging

**Comment by Woozl** [comment]
To elaborate, there are potential errors that the UI can't know about, so the current behavior of the UI is to throw these "unknown" error messages.

**Comment by karafecho** [comment]
IF you and Hina cannot reproduce the issue (posted in MAR2023), then we can close it.

**Comment by EvanDietzMorris** [comment]
I just ran this and it did complete successfully and pretty fast, so let's use the other issues to address the error messaging.
