### ISSUE TITLE
Automat landing page - rename

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#116]
This issue is to suggest that you rename the [Automat landing page](https://robokopu24.github.io/api-docs/), given that this site links out from the main [ROBOKOP landing page](https://robokopu24.github.io/landing-page/). I suggest the following:

1. Main header: "ROBOKOP".
2. Sub-header: "Automat".

I realize, however, that Automat also supports ARAGORN, etc. So another option is to define the relationship between ROBOKOP and Automat on the main ROBOKOP landing page. I've included this option in my text suggestions for that page.

**Comment by cbizon** [comment]
We will review the headings on 3/20.   I think for the page that is being developed as the swagger replacement that can be robokop branded.

**Comment by Woozl** [comment]
Docs site is now just branded as ROBOKOP
