### ISSUE TITLE
Automat API Documentation - human-readable text descriptions are missing

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#117]
The updated API Documentation is a big improvement and really nice. However, what is missing is simple two-sentence descriptions of each data source and endpoint in a human-readable format, with a link to an external source (e.g., CTD's main page) when available. This will be critical for subject matter experts who are not developers.

**Comment by cbizon** [comment]
Discussed at the 3/13 UI meeting

**Comment by Woozl** [comment]
From #119 

> - OpenAPI supports CommonMark markdown in the description tags, which is rendered as rich text on the new docs site. All "human-readable" documentation can live alongside the the schema in the json doc. We can also host images for the documentation if necessary for diagrams, etc.
>     - you can try this out on the [Swagger editor](https://editor.swagger.io/) as well
>     - [Markdown](https://commonmark.org/help/), if unfamiliar

**Comment by karafecho** [comment]
I am familiar with markdown and have worked with Swagger editors. The question is who will be providing the text. I am happy to do so, but I do not want to duplicate efforts.

**Comment by Woozl** [comment]
graph descriptions are returned by the `/metadata` endpoint, see #126
