### ISSUE TITLE
Automat - broken API requests

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#118]
This issue is to report that some, but not all, API requests are broken in Automat. I did not track this systematically, but I'd advise the developer team to test each and every feature/item.

**Comment by cbizon** [comment]
@karafecho can you provide any details here?  Were you writing api calls? Using the swagger ui? something else?

**Comment by karafecho** [comment]
Sure thing. I was testing the various "Send API Request" buttons for the different resources listed under Automat. Some returned a JSON response; others didn't. I didn't notice any sort of systematic issue, e.g., all of the "Meta knowledge graph representation of this TRAPI web service" features were broken, but I didn't run any systematic tests. Hope this helps ...

**Comment by Woozl** [comment]
@karafecho I updated the docs site 2 days ago to use the up-to-date API spec (more info in #120). Could you let me know if it's fixed for you? Everything seems to work now for me.

**Comment by Woozl** [comment]
I believe this was an issue with the api being updated before the docs site was built, should be fixed now
