### ISSUE TITLE
ROBOKOP UI: Capitalization (minor issue)

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#21]
This issue is to request that all text instances of "Robokop" be replaced with "ROBOKOP". While this may sound picky, in my mind, consistency is important to demonstrate a competitive scientific product rather than an academic R&D product.

**Comment by cbizon** [comment]
I think that this is corrected.  @karafecho please reopen if necessary.

**Comment by karafecho** [comment]
The GitHub org is still "RobokopU24" rather than "ROBOKOP", but we've probably done too much advertising at this point to change it. Noting it here in case @cbizon thinks we should change it.
