### ISSUE TITLE
Publication support for edges in answer subgraphs

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#99]
This issue is to report that publication support for edges is largely absent from ROBOKOP results.  Related, if I run a multi-hop query, I cannot click on edges in the "Answer Explorer" to find additional publication support, nor can I determine the provenance of any of the edges or the nodes. There's ranking of answers, but it's not clear what those rankings are based on. This is probably a known issue(s), but I wanted to report it and suggest that the team prioritizes it. 

This issue is a bit packed and may need to be dissected.

**Comment by cbizon** [comment]
I'm not sure what we can do here.  If the source doesn't have publications, it doesn't have publications...  @eKathleenCarter maybe we should review the sources to make sure that we're getting everything that there is...

**Comment by karafecho** [comment]
I think this issue was due to the UI not displaying all of the pub information available in the JSON response. Since resolved. The other issue noted here was related to documentation on the scoring-and-ranking algorithm. Also resolved. As such, I'm closing the ticket ...
